DROP TABLE employees IF EXISTS;
DROP TABLE taskss IF EXISTS;

CREATE TABLE employees (
  id INTEGER,
  first_name VARCHAR(30),
  last_name VARCHAR(30),
  position VARCHAR(30),
  address VARCHAR(50),
  phone VARCHAR(30),
  manager_name VARCHAR(30),
  primary key (id)
);

CREATE TABLE tasks (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_id INTEGER,
  task_text VARCHAR(80),
  assign_date VARCHAR(30),
  due_date VARCHAR(30)
);